<?php
// https://isabelcastillo.com/list-capabilities-current-user-wordpress

function wptd_set_capabilities()
{
   // get custom roles
   $role_admin = get_role('admin');

   // remove all capabilities from custom roles
   $remove_capabilities = array(
      'switch_themes',
      'edit_themes',
      'activate_plugins',
      'edit_plugins',
      'edit_users',
      'edit_files',
      'manage_options',
      'moderate_comments',
      'manage_categories',
      'manage_links',
      'upload_files',
      'import',
      'unfiltered_html',
      'edit_posts',
      'edit_others_posts',
      'edit_published_posts',
      'publish_posts',
      'edit_pages',
      'read',
      'level_10',
      'level_9',
      'level_8',
      'level_7',
      'level_6',
      'level_5',
      'level_4',
      'level_3',
      'level_2',
      'level_1',
      'level_0',
      'edit_others_pages',
      'edit_published_pages',
      'publish_pages',
      'delete_pages',
      'delete_others_pages',
      'delete_published_pages',
      'delete_posts',
      'delete_others_posts',
      'delete_published_posts',
      'delete_private_posts',
      'edit_private_posts',
      'read_private_posts',
      'delete_private_pages',
      'edit_private_pages',
      'read_private_pages',
      'delete_users',
      'create_users',
      'unfiltered_upload',
      'edit_dashboard',
      'update_plugins',
      'delete_plugins',
      'install_plugins',
      'update_themes',
      'install_themes',
      'update_core',
      'list_users',
      'remove_users',
      'add_users',
      'promote_users',
      'edit_theme_options',
      'delete_themes',
      'export',
      'administrator',
   );
   foreach ($remove_capabilities as $remove_capability) {
      $role_admin->remove_cap($remove_capability);
   }

   // set capabilities for role admin
   $role_admin_capabilities = array(
      'switch_themes',
      'activate_plugins',
      'edit_plugins',
      'edit_users',
      'edit_files',
      'manage_options',
      'moderate_comments',
      'manage_categories',
      'manage_links',
      'upload_files',
      'import',
      'unfiltered_html',
      'edit_posts',
      'edit_others_posts',
      'edit_published_posts',
      'publish_posts',
      'edit_pages',
      'read',
      'level_9',
      'level_8',
      'level_7',
      'level_6',
      'level_5',
      'level_4',
      'level_3',
      'level_2',
      'level_1',
      'level_0',
      'edit_others_pages',
      'edit_published_pages',
      'publish_pages',
      'delete_pages',
      'delete_others_pages',
      'delete_published_pages',
      'delete_posts',
      'delete_others_posts',
      'delete_published_posts',
      'delete_private_posts',
      'edit_private_posts',
      'read_private_posts',
      'delete_private_pages',
      'edit_private_pages',
      'read_private_pages',
      'delete_users',
      'create_users',
      'unfiltered_upload',
      'edit_dashboard',
      'update_plugins',
      'delete_plugins',
      'install_plugins',
      'update_core',
      'list_users',
      'remove_users',
      'add_users',
      'export',
   );
   foreach ($role_admin_capabilities as $role_admin_capability) {
      $role_admin->add_cap($role_admin_capability);
   }
}

add_action('init', 'wptd_set_capabilities');
